# Generated by Django 3.2.7 on 2021-11-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=100)),
                ('video', models.FileField(blank=True, null=True, upload_to='uploads/video')),
                ('desc', models.TextField(blank=True, max_length=1200, null=True)),
            ],
        ),
    ]
