# Generated by Django 3.2.7 on 2021-11-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
